---
- hosts: localhost
  become: true
  connection: local
  tasks:
    - name: Configuring Redis Input
      replace:
        regexp: "redisinput"
        replace: "{{ redis_server }}"
        dest: "/etc/logstash/conf.d/processor_000_inputs.conf"

    - name: Configuring ES Output
      replace:
        regexp: "esoutput"
        replace: "{{ es_server }}"
        dest: "/etc/logstash/conf.d/pre_processor_999_outputs.conf"
